<?php
/**
 * @file
 * Code for the eReolen help module feature.
 */

include_once 'reol_help.features.inc';
/**
 * @file
 * Code for the eReolen help feature module.
 */

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_help_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view faq page',
    ),
    'authenticated user' => array(
      'view faq page',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Alter variables to be able to create our own markup for the faq-page.
 */
function reol_help_preprocess_faq_category_new_page(&$variables) {
  // We need a way to see whether or not we are at the first level. Do this
  // using category_depth and display_header. The template will be called with
  // category_depth = 0 even when on the page for a level down, but
  // display_header will be false at that point. So if we are at something lower
  // than level 0 or display_header is disabled.
  $variables['first_level'] = $variables['category_depth'] == 0 && $variables['display_header'];

  // Remove weirdly formatted description, and replace with regular one.
  $variables['description'] = $variables['term']->description;

  // Extract the real title, instead of linked one.
  $variables['title'] = $variables['term']->name;

  // Extract the link for the faq-page.
  $variables['link'] = url('faq-page/' . $variables['term']->tid);

  // Stuff for first-level:
  if ($variables['first_level']) {
    // Get the image for the category, if defined.
    if (!empty($variables['term']->field_image[LANGUAGE_NONE][0])) {
      $variables['image'] = image_style_url('reol_faq_category_image', $variables['term']->field_image[LANGUAGE_NONE][0]['uri']);
    }
  }
}
