<?php
/**
 * @file
 * Code for the eReolen help module feature.
 */

include_once 'reol_help.features.inc';
/**
 * @file
 * Code for the eReolen help feature module.
 */

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_help_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view faq page',
    ),
    'authenticated user' => array(
      'view faq page',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Alter variables to be able to create our own markup for the faq-page.
 */
function reol_help_preprocess_faq_category_new_page(&$variables) {
  // We need a way to see whether or not we are at the first level. Do this
  // using category_depth and display_header. The template will be called with
  // category_depth = 0 even when on the page for a level down, but
  // display_header will be false at that point. So if we are at level 0 and we
  // are displaying the header, we are at first level.
  $variables['first_level'] = $variables['category_depth'] == 0 && $variables['display_header'];

  // Second level is specified when we are at category_depth 0, and are not
  // showing title. This is because, when showing page for second level, the
  // first level will be processed, but without showing the header.
  $variables['second_level'] = $variables['category_depth'] == 0 && !$variables['display_header'];

  // For now, we support those two levels, everything else is just questions.
  $variables['questions_level'] = !$variables['first_level'] && !$variables['second_level'];

  // Remove weirdly formatted description, and replace with regular one.
  $variables['description'] = $variables['term']->description;

  // Extract the real title, instead of linked one.
  $variables['title'] = $variables['term']->name;

  // Extract the link for the faq-page.
  $variables['link'] = url('faq-page/' . $variables['term']->tid);

  // Stuff for first-level:
  if ($variables['first_level']) {
    // Get the image for the category, if defined.
    if (!empty($variables['term']->field_image[LANGUAGE_NONE][0])) {
      $variables['image'] = image_style_url('reol_faq_category_image', $variables['term']->field_image[LANGUAGE_NONE][0]['uri']);
    }
  }
  // Stuff for second level.
  elseif ($variables['second_level']) {
    drupal_add_js(drupal_get_path('module', 'reol_help') . '/js/faq-category-page.js');

    $variables['category_title'] = reol_help_get_text_field_value($variables['term'], 'field_page_title');
    $variables['category_lead'] = reol_help_get_text_field_value($variables['term'], 'field_ding_page_lead');
    $variables['category_body'] = reol_help_get_text_field_value($variables['term'], 'field_ding_page_body');
  }
}

/**
 * Get the value of a text field, on an entity.
 */
function reol_help_get_text_field_value($entity, $field_name, $default = '') {
  if (!empty($entity->{$field_name}[LANGUAGE_NONE][0]['value'])) {
    return $entity->{$field_name}[LANGUAGE_NONE][0]['value'];
  }

  return $default;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function reol_help_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}
