<?php
/**
 * @file
 * Code for the eReolen help feature module.
 */

include_once 'reol_help.features.inc';

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_help_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view faq page',
    ),
    'authenticated user' => array(
      'view faq page',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Alter variables to be able to create our own markup for the faq-page.
 */
function reol_help_preprocess_faq_category_new_page(&$variables) {
  // We need a way to see whether or not we are at the first level. Do this
  // using category_depth and display_header. The template will be called with
  // category_depth = 0 even when on the page for a level down, but
  // display_header will be false at that point. So if we are at something lower
  // than level 0 or display_header is disabled.
  $variables['first_level'] = $variables['category_depth'] > 0 || !$variables['display_header'];
}
