<?php
/**
 * @file
 * Installation of reol_help module.
 */

/**
 * Apply FAQ-module settings.
 */
function reol_help_update_7001() {
  // Category settings.
  variable_set('faq_use_categories', TRUE);
  variable_set('faq_count', FALSE);
  variable_set('faq_hide_child_terms', TRUE);
  variable_set('faq_category_display', 'hide_qa');

  // Question settings.
  variable_set('faq_display', 'new_page');
  variable_set('faq_question_length', 'short');
}
